# Generated by Django 5.1 on 2024-08-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVKM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_text', models.CharField(max_length=200)),
                ('noOfPeopleInDepartment', models.IntegerField()),
                ('headofDepartmentName', models.CharField(max_length=100)),
                ('departmentPhoneno', models.IntegerField()),
                ('departmentEmailId', models.EmailField(max_length=254)),
            ],
        ),
    ]
